SRCH-2593 updating translation guidance
GSA/punchcard pull request #52
Opened 2021-11-09 21:03 UTC by amanifarooque

2021-11-15 15:40 UTC, MothOnMars requested changes
a couple of copy edits

2021-11-15 16:29 UTC, amanifarooque commented on CONTRIBUTING.md
>  #### Be Patient
I'm in favor of removing that "Be Patient" section entirely, I don't think it adds anything.

2021-11-15 16:48 UTC, MothOnMars commented on CONTRIBUTING.md
>  #### Be Patient
Works for me!

2021-11-15 17:53 UTC, amanifarooque commented on CONTRIBUTING.md
> +Punchcard is work of [multiple contributors](https://github.com/GSA/punchcard/graphs/contributors). You're encouraged to submit [pull requests](https://github.com/GSA/punchcard/pulls), [propose featu
Updated!

2021-11-15 17:53 UTC, amanifarooque commented on CONTRIBUTING.md
>  #### Be Patient
Removed!

2021-11-15 18:04 UTC, MothOnMars approved these changes
LGTM

2021-11-17 15:57 UTC, amanifarooque commented
Removing Dawn as a reviewer as we've gotten her feedback via Slack.

2021-11-17 15:57 UTC, merged